### PR TITLE
CI: add clang-format check

### PR DESCRIPTION
**Pull request by pjonsson**

### CODE REVIEW

**Comment by kffaxen** [comment]
Vill du som vet vat du avsåg resolva konflikterna?

**Comment by pjonsson** [comment]
Fixed conflicts. This should fail the CI.

**Comment by kffaxen** [comment]
Nope, succeeded!

**Comment by kffaxen** [comment]
In my interface, it seems it got through. What does it look like from your side?

**Comment by kffaxen** [comment]
Spänningen är oliiiiidlig...

**Comment by pjonsson** [comment]
Github only fetches pull requests with depth 1 by default so git-clang-format did not have anything to compare against. After fixing that we get a failed action if the code is badly formatted according to clang-format.

This pull request is ready to be merged.

**Comment by kffaxen** [comment]
Sometimes failure is success!

**Pull request merged**
